# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

similarityCount <- function(mat, r) {
    .Call('_MSMVSampEn_similarityCount', PACKAGE = 'MSMVSampEn', mat, r)
}

vectorEmbed <- function(mat, M, tau) {
    .Call('_MSMVSampEn_vectorEmbed', PACKAGE = 'MSMVSampEn', mat, M, tau)
}

